#!/usr/bin/env python3
"""
Turok 2 MP — Loadout / Attribute config editor

Builds and parses multiplayer-style key lines the EXE understands
(format strings in Turok2MP.exe: \\TurokAttribs\\%s, \\SpeedMultiplier\\%f, …).

  python t2_loadout.py template -o my_loadout.json
  python t2_loadout.py export my_loadout.json -o integrated.cfg
  python t2_loadout.py import integrated.cfg -o my_loadout.json
  python t2_loadout.py list-weapons

Place exported .cfg next to the game / as ./integrated.cfg for integrated server,
or merge keys into your normal MP config. Live memory apply is separate (t2_cheats).
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, List, Optional

CHARACTERS = [
    "Turok",
    "Adon",
    "Raptor",
    "Telset",
    "Campaigner",
    "Iggy",
    "Fireborn",
    "Endtrail",
    "Purrlin",
    "Flesheater",
    "Gant",
]

# From Turok2MP.exe ArenaWeapons / weapon name table
WEAPONS = [
    "Pistol",
    "Magnum Pistol",
    "Shotgun",
    "Charge Dart Rifle",
    "Tek Bow",
    "Plasma Rifle",
    "Shredder (Shrapnel Cannon)",
    "Grenade Launcher",
    "Scorpion Rocket Launcher",
    "Firestorm Cannon",
    "Flame Thrower",
    "Cerebral Bore",
    "Nuke",
]

# Attrib string is free-form in the EXE (%s). Common community / logical fields
# are stored as a single token string until we map exact internal grammar.
DEFAULT_ATTRIB = "default"

DEFAULT_LOADOUT: Dict[str, Any] = {
    "meta": {
        "game": "Turok2MP",
        "notes": "Export to .cfg and place as integrated.cfg or merge into MP config.",
    },
    "global": {
        "SpeedMultiplier": 1.0,
        "DamageMultiplier": 1.0,
        "NodeExpansion": 1.0,
        "ArenaHealth": 100,
        "ArenaMaxAmmo": True,
        "ArenaWeapons": "(all)",  # or comma-separated subset
        "EnemiesDropWeapons": True,
        "WeaponsRemain": True,
        "AllCharactersSame": False,
    },
    "characters": {
        name: {
            "Attribs": DEFAULT_ATTRIB,
            "StartAmmo": "default",
            "MaxAmmo": "default",
        }
        for name in CHARACTERS
    },
}


def template() -> Dict[str, Any]:
    return json.loads(json.dumps(DEFAULT_LOADOUT))  # deep copy


def save_json(data: Dict[str, Any], path: Path) -> None:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def export_cfg(data: Dict[str, Any]) -> str:
    """Write key lines matching EXE format strings (backslash keys)."""
    lines: List[str] = [
        "; Turok 2 MP loadout — generated by t2_loadout.py",
        "; Keys mirror Turok2MP.exe config tokens.",
        "",
    ]
    g = data.get("global", {})
    def emit(key: str, val: Any) -> None:
        if isinstance(val, bool):
            lines.append(f"\\{key}\\{'TRUE' if val else 'FALSE'}")
        elif isinstance(val, float):
            lines.append(f"\\{key}\\{val}")
        elif isinstance(val, int):
            lines.append(f"\\{key}\\{val}")
        else:
            lines.append(f"\\{key}\\{val}")

    for key in (
        "SpeedMultiplier",
        "DamageMultiplier",
        "NodeExpansion",
        "ArenaHealth",
        "ArenaMaxAmmo",
        "ArenaWeapons",
        "EnemiesDropWeapons",
        "WeaponsRemain",
        "AllCharactersSame",
    ):
        if key in g:
            emit(key, g[key])

    lines.append("")
    chars = data.get("characters", {})
    for name in CHARACTERS:
        c = chars.get(name, {})
        if not c:
            continue
        lines.append(f"; --- {name} ---")
        if "Attribs" in c:
            emit(f"{name}Attribs", c["Attribs"])
        if "StartAmmo" in c:
            emit(f"{name}StartAmmo", c["StartAmmo"])
        if "MaxAmmo" in c:
            emit(f"{name}MaxAmmo", c["MaxAmmo"])
        lines.append("")
    return "\n".join(lines)


def import_cfg(text: str) -> Dict[str, Any]:
    data = template()
    # \\Key\\value  or Key = value
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith(";") or line.startswith("#"):
            continue
        m = re.match(r"^\\([^\\]+)\\(.*)$", line)
        if m:
            key, val = m.group(1), m.group(2).strip()
        elif "=" in line:
            key, val = [x.strip() for x in line.split("=", 1)]
        else:
            continue
        # global
        if key in data["global"]:
            cur = data["global"][key]
            if isinstance(cur, bool):
                data["global"][key] = val.upper() in ("1", "TRUE", "YES", "ON")
            elif isinstance(cur, float):
                try:
                    data["global"][key] = float(val)
                except ValueError:
                    pass
            elif isinstance(cur, int):
                try:
                    data["global"][key] = int(float(val))
                except ValueError:
                    pass
            else:
                data["global"][key] = val
            continue
        # character fields
        for name in CHARACTERS:
            for field, suffix in (("Attribs", "Attribs"), ("StartAmmo", "StartAmmo"), ("MaxAmmo", "MaxAmmo")):
                if key == f"{name}{suffix}":
                    data["characters"].setdefault(name, {})[field] = val
    return data


def apply_preset(data: Dict[str, Any], preset: str) -> Dict[str, Any]:
    """Named gameplay presets layered on template."""
    g = data.setdefault("global", {})
    if preset == "glass_cannon":
        g["DamageMultiplier"] = 2.0
        g["ArenaHealth"] = 50
    elif preset == "tank":
        g["DamageMultiplier"] = 0.5
        g["ArenaHealth"] = 200
    elif preset == "speed":
        g["SpeedMultiplier"] = 1.5
    elif preset == "pistols_only":
        g["ArenaWeapons"] = "Pistol,Magnum Pistol"
        g["ArenaMaxAmmo"] = True
    elif preset == "heavy":
        g["ArenaWeapons"] = "Nuke,Flame Thrower,Scorpion Rocket Launcher,Cerebral Bore,Firestorm Cannon"
    elif preset == "vanilla":
        data.clear()
        data.update(template())
    else:
        raise SystemExit(f"Unknown preset: {preset}")
    return data


def main() -> None:
    ap = argparse.ArgumentParser(description="Turok 2 MP loadout / attribute editor")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("template")
    p.add_argument("-o", "--output", type=Path, default=Path("t2_loadout.json"))

    p = sub.add_parser("export")
    p.add_argument("json_path", type=Path)
    p.add_argument("-o", "--output", type=Path, default=Path("integrated.cfg"))

    p = sub.add_parser("import")
    p.add_argument("cfg_path", type=Path)
    p.add_argument("-o", "--output", type=Path, default=Path("t2_loadout.json"))

    p = sub.add_parser("preset")
    p.add_argument("name", choices=("glass_cannon", "tank", "speed", "pistols_only", "heavy", "vanilla"))
    p.add_argument("-o", "--output", type=Path, default=Path("t2_loadout.json"))

    sub.add_parser("list-weapons")
    sub.add_parser("list-characters")

    args = ap.parse_args()
    if args.cmd == "template":
        save_json(template(), args.output)
        print(f"Wrote template {args.output}")
    elif args.cmd == "export":
        data = load_json(args.json_path)
        args.output.write_text(export_cfg(data), encoding="utf-8")
        print(f"Exported {args.output}")
    elif args.cmd == "import":
        data = import_cfg(args.cfg_path.read_text(encoding="utf-8", errors="replace"))
        save_json(data, args.output)
        print(f"Imported -> {args.output}")
    elif args.cmd == "preset":
        data = apply_preset(template(), args.name)
        save_json(data, args.output)
        print(f"Preset {args.name} -> {args.output}")
    elif args.cmd == "list-weapons":
        for w in WEAPONS:
            print(w)
    elif args.cmd == "list-characters":
        for c in CHARACTERS:
            print(c)


if __name__ == "__main__":
    main()
